services:
  brain-farm-database:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brain_farm
    volumes:
      - ./.docker:/docker-entrypoint-initdb.d